<h3>GIS Tasks v128</h3>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">All</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Login / Logout - <em>task</em></span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Events (School Calendar)</span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Teacher</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage (add, edit) class records (Grades / Scores)</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;"><span style="font-family: 'Times New Roman', serif; font-size: 12pt;">Finalize Class Records (observe deadline) - Average and Course Ranks</span></span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Adviser</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage class attendance and finalize</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Check Class Matrix </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Monitor submissions and follow up pending class records</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Finalize class Conducts / Traits</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Tally Aggregates and Finalize - i.e. MAPEH</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Summarizer - class general averages</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">QCR - class ranking</span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Subject Area Coordinator (SAC)</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View subject area class records</span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Academic Head / Principal</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View all class records</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View all class lists</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View basic profiling</span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Registrar</span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Print Report Cards (also by GIS Coordinator)</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage class lists</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Register new student/s</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View Class Records - Ranks, Profiles, Grades</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Enrollment of student/s</span></li>
</ol>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">MIS / GIS Coordinator </span></span></p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Change or adjust records</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage &amp; Register contacts accounts</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Setup GIS data - criteria, subjects, levels, sections, courses, teachers' loads </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage GIS Settings, i.e. school year &amp; quarter, transmutation and computing algorithms </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">View records statistics from dashboard</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Setup misc data - attendance months and days, </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Transfer students to another section (same grade level)</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Manage locking - both Courses and Advisory Classes</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Configure subjects courses - teacher, weight, components, position, label, computing algorithm, etc.</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Has basic understanding of GIS Book / Brochure (Follow flowchart instructions) </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Get signature for conditions from concerned school personnel (i.e. report card layout - Registrar, settings config - Academic Coordinator)</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Print report cards every quarter (or by Registrar)</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Assign SAC and class advisers</span></li>
</ol>
<p class="MsoNormal" style="margin: 0in 0in 12pt 0.5in;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 12pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">PCMed ISO </span></span></p>
<p>&nbsp;</p>
<ol style="margin-top: 0in;" type="1" start="1">
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">DTR / Daily Task Report thru SMS and Spreadsheet</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">a) Meeting and Communicating with client's MIS / GIS Coordinator regularly and b) update GIS Annual Report</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Quarterly, Semestral Backup of GIS Database&nbsp; </span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Organize GIS documents, i.e. request forms, letters, updates, clients reports, conditions / compliance, service orders, etc</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Secure the signed GIS Conditions (compliance) from clients</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Support a) GIS concerns like changing of quarter, floor grade settings values &amp; b) MIS functions</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Annual Setup of GIS for new school year</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Train clients (Registrar / MIS) with enrollment and student registration every new school year</span></li>
<li class="MsoNormal" style="margin-bottom: 12pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: ZH-CN;">Train clients (Registrar / MIS) with the use of GIS Book instructions, i.e. transfer students, print report cards, change grades and summarize,&nbsp;</span></li>
</ol>